import os
import pathlib
import plistlib
import subprocess
import tempfile
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
AI_TOKEN = ROOT / "ai-token"


class ServiceEnvironmentTest(unittest.TestCase):
    @staticmethod
    def wrapper_environment(home):
        binary = home / "fake-bin"
        binary.mkdir()
        for name, body in {
            "crontab": (
                '#!/usr/bin/env bash\nif [ "${1:-}" = -l ]; then\n'
                '  [ ! -f "$CRONTAB_FILE" ] || cat "$CRONTAB_FILE"\n'
                'else\n  cat > "$CRONTAB_FILE"\nfi\n'
            ),
            "launchctl": '#!/usr/bin/env bash\nprintf "%s\\n" "$*" >> "$LAUNCHCTL_CALLS"\n',
            "uname": '#!/usr/bin/env bash\necho "${FAKE_UNAME:-Linux}"\n',
        }.items():
            path = binary / name
            path.write_text(body)
            path.chmod(0o755)
        return {
            **os.environ,
            "HOME": str(home),
            "AI_TOKEN_REAL_HOME": str(home),
            "CLAUDE_TOKEN_WRAPPER_DIR": str(home / "wrappers"),
            "CRONTAB_FILE": str(home / "crontab"),
            "LAUNCHCTL_CALLS": str(home / "launchctl.calls"),
            "PATH": f"{binary}:/usr/bin:/bin",
        }

    def test_generated_wrappers_pin_the_invoked_canonical_binary(self):
        with tempfile.TemporaryDirectory() as directory:
            home = pathlib.Path(directory)
            env = self.wrapper_environment(home)

            for backend in ("codex", "claude"):
                result = subprocess.run(
                    [AI_TOKEN, backend, "install-wrapper"],
                    env=env,
                    text=True,
                    capture_output=True,
                    timeout=10,
                )
                self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn(f'exec {AI_TOKEN} codex run "$@"', (home / "bin" / "codex").read_text())
            self.assertIn(f'exec {AI_TOKEN} claude run "$@"', (home / "bin" / "claude").read_text())

            follower_config = home / ".claude-token" / "followers" / "fixture" / "config"
            follower_config.parent.mkdir(parents=True)
            follower_config.write_text("user=fixture\nmode=follower\n")
            wrapper = home / "wrappers" / "claude-fixture"
            wrapper.parent.mkdir()
            wrapper.write_text(
                '#!/usr/bin/env bash\n# generated by claude-token named follower\n'
                'exec claude-token run-follower "fixture" "$@"\n'
            )
            wrapper.chmod(0o755)
            result = subprocess.run(
                [AI_TOKEN, "claude", "install-follower-wrapper", "fixture"],
                env=env,
                text=True,
                capture_output=True,
                timeout=10,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn(f'exec {AI_TOKEN} claude run-follower "fixture" "$@"', wrapper.read_text())
            self.assertNotIn("exec claude-token ", wrapper.read_text())

            result = subprocess.run(
                [AI_TOKEN, "claude", "install-profile-wrapper", "fixture"],
                env=env,
                text=True,
                capture_output=True,
                timeout=10,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            profile_wrapper = home / ".local" / "bin" / "claude-fixture"
            self.assertIn(f'"$({AI_TOKEN} claude proxy-url fixture)"', profile_wrapper.read_text())
            self.assertNotIn("$(claude-token ", profile_wrapper.read_text())

    def test_maintenance_replaces_obsolete_writer_and_authority(self):
        with tempfile.TemporaryDirectory() as directory:
            home = pathlib.Path(directory)
            env = self.wrapper_environment(home)
            crontab = home / "crontab"
            crontab.write_text(
                "17 * * * * /usr/bin/unrelated\n"
                "1 */2 * * * CLAUDE_TOKEN_VAULT_AUTHORITY=yes /stale/ai-token claude maintain "
                ">/dev/null 2>&1 # claude-token-maintain\n"
            )

            result = subprocess.run(
                [AI_TOKEN, "claude", "install-maintenance"],
                env=env,
                text=True,
                capture_output=True,
                timeout=10,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            lines = crontab.read_text().splitlines()
            self.assertIn("17 * * * * /usr/bin/unrelated", lines)
            managed = [line for line in lines if line.endswith("# claude-token-maintain")]
            self.assertEqual(len(managed), 1)
            self.assertIn(f" {AI_TOKEN} claude maintain ", managed[0])
            self.assertNotIn("/stale/ai-token", managed[0])
            self.assertNotIn("CLAUDE_TOKEN_VAULT_AUTHORITY=yes", managed[0])

            result = subprocess.run(
                [AI_TOKEN, "claude", "install-maintenance"],
                env={**env, "CLAUDE_TOKEN_VAULT_AUTHORITY": "yes"},
                text=True,
                capture_output=True,
                timeout=10,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            managed = [
                line for line in crontab.read_text().splitlines()
                if line.endswith("# claude-token-maintain")
            ]
            self.assertEqual(len(managed), 1)
            self.assertIn("CLAUDE_TOKEN_VAULT_AUTHORITY=yes", managed[0])

    def test_launchd_maintenance_rewrites_authority_with_canonical_binary(self):
        with tempfile.TemporaryDirectory() as directory:
            home = pathlib.Path(directory)
            env = {
                **self.wrapper_environment(home),
                "FAKE_UNAME": "Darwin",
                "CLAUDE_TOKEN_MAINTENANCE_DIR": str(home / "LaunchAgents"),
                "CLAUDE_TOKEN_VAULT_AUTHORITY": "yes",
            }
            command = [AI_TOKEN, "claude", "install-maintenance"]
            first = subprocess.run(command, env=env, text=True, capture_output=True, timeout=10)
            self.assertEqual(first.returncode, 0, first.stderr)
            plist = home / "LaunchAgents" / "com.krandder.claude-token-maintain.plist"
            with plist.open("rb") as handle:
                data = plistlib.load(handle)
            self.assertEqual(data["ProgramArguments"], [str(AI_TOKEN), "claude", "maintain"])
            self.assertEqual(data["EnvironmentVariables"]["CLAUDE_TOKEN_VAULT_AUTHORITY"], "yes")

            env.pop("CLAUDE_TOKEN_VAULT_AUTHORITY")
            second = subprocess.run(command, env=env, text=True, capture_output=True, timeout=10)
            self.assertEqual(second.returncode, 0, second.stderr)
            with plist.open("rb") as handle:
                data = plistlib.load(handle)
            self.assertNotIn("CLAUDE_TOKEN_VAULT_AUTHORITY", data["EnvironmentVariables"])
            calls = (home / "launchctl.calls").read_text()
            self.assertIn("bootout", calls)
            self.assertIn("bootstrap", calls)

    def test_proxy_unit_pins_the_invoked_canonical_binary_and_service_path(self):
        with tempfile.TemporaryDirectory() as directory:
            home = pathlib.Path(directory)
            binary = home / "bin"
            binary.mkdir()
            calls = home / "systemctl.calls"
            systemctl = binary / "systemctl"
            systemctl.write_text(f"#!/usr/bin/env bash\nprintf '%s\\n' \"$*\" >> {calls}\n")
            systemctl.chmod(0o755)
            stale = binary / "claude-token"
            stale.write_text("#!/usr/bin/env bash\necho stale-writer\n")
            stale.chmod(0o755)
            env = {
                **os.environ,
                "HOME": str(home),
                "AI_TOKEN_REAL_HOME": str(home),
                "PATH": f"{binary}:/usr/bin:/bin",
            }
            result = subprocess.run(
                [AI_TOKEN, "claude", "proxy-install"],
                env=env,
                text=True,
                capture_output=True,
                timeout=10,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            unit = (home / ".config" / "systemd" / "user" / "claude-token-proxy.service").read_text()
            self.assertIn(f"ExecStart={AI_TOKEN} claude proxy", unit)
            self.assertIn(f"Environment=PATH={ROOT}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin", unit)
            self.assertNotIn(str(stale), unit)
            self.assertIn("daemon-reload", calls.read_text())


if __name__ == "__main__":
    unittest.main()
