import os
import pathlib
import subprocess
import tempfile
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
AI_TOKEN = ROOT / "ai-token"


class GeneratedWriteSafetyTest(unittest.TestCase):
    def environment(self, root, *, uname="Linux"):
        home = root / "home"
        binary = root / "bin"
        home.mkdir()
        binary.mkdir()
        scripts = {
            "uname": "#!/bin/sh\nprintf '%s\\n' \"$FAKE_UNAME\"\n",
            "systemctl": "#!/bin/sh\nexit 0\n",
            "launchctl": "#!/bin/sh\nexit 0\n",
            "crontab": (
                "#!/bin/sh\n"
                "if [ \"${1:-}\" = -l ]; then\n"
                "  [ ! -f \"$CRONTAB_FILE\" ] || cat \"$CRONTAB_FILE\"\n"
                "else\n"
                "  cat > \"$CRONTAB_FILE\"\n"
                "fi\n"
            ),
        }
        for name, source in scripts.items():
            path = binary / name
            path.write_text(source)
            path.chmod(0o755)
        return home, {
            **os.environ,
            "HOME": str(home),
            "AI_TOKEN_REAL_HOME": str(home),
            "CLAUDE_TOKEN_WRAPPER_DIR": str(home / "wrappers"),
            "CLAUDE_TOKEN_MAINTENANCE_DIR": str(home / "LaunchAgents"),
            "CRONTAB_FILE": str(home / "crontab"),
            "FAKE_UNAME": uname,
            "PATH": f"{binary}:/usr/bin:/bin",
        }

    def run_token(self, environment, *arguments):
        return subprocess.run(
            [AI_TOKEN, *arguments],
            env=environment,
            text=True,
            capture_output=True,
            timeout=15,
        )

    def assert_symlink_is_replaced_without_touching_target(
        self, arguments, destination_for, *, prepare=None, uname="Linux",
    ):
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            home, environment = self.environment(root, uname=uname)
            destination = destination_for(home)
            destination.parent.mkdir(parents=True, exist_ok=True)
            victim = root / "unrelated-state"
            victim.write_text("do-not-touch\n")
            destination.symlink_to(victim)
            if prepare is not None:
                prepare(home, destination, victim)
            before = victim.read_bytes()

            result = self.run_token(environment, *arguments)

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(victim.read_bytes(), before)
            self.assertFalse(destination.is_symlink())
            self.assertTrue(destination.is_file())

    def test_generated_entrypoints_never_follow_destination_symlinks(self):
        def existing_backup(_home, destination, _victim):
            pathlib.Path(str(destination) + ".pre-codex-token").write_text("existing backup\n")

        def existing_claude_backup(_home, destination, _victim):
            pathlib.Path(str(destination) + ".pre-claude-token").write_text("existing backup\n")

        def stale_named_follower(home, _destination, victim):
            config = home / ".claude-token" / "followers" / "fixture" / "config"
            config.parent.mkdir(parents=True)
            config.write_text("user=fixture\nmode=follower\n")
            victim.write_text(
                "#!/usr/bin/env bash\n"
                "# generated by claude-token named follower\n"
                "exec /stale/ai-token claude run-follower \"fixture\" \"$@\"\n"
            )

        cases = (
            (
                "codex-wrapper",
                ("codex", "install-wrapper"),
                lambda home: home / "bin" / "codex",
                existing_backup,
                "Linux",
            ),
            (
                "claude-wrapper",
                ("claude", "install-wrapper"),
                lambda home: home / "bin" / "claude",
                existing_claude_backup,
                "Linux",
            ),
            (
                "named-follower-wrapper",
                ("claude", "install-follower-wrapper", "fixture"),
                lambda home: home / "wrappers" / "claude-fixture",
                stale_named_follower,
                "Linux",
            ),
            (
                "profile-wrapper",
                ("claude", "install-profile-wrapper", "fixture"),
                lambda home: home / ".local" / "bin" / "claude-fixture",
                None,
                "Linux",
            ),
            (
                "proxy-unit",
                ("claude", "proxy-install"),
                lambda home: home / ".config" / "systemd" / "user" / "claude-token-proxy.service",
                None,
                "Linux",
            ),
            (
                "launchd-plist",
                ("claude", "install-maintenance"),
                lambda home: home / "LaunchAgents" / "com.krandder.claude-token-maintain.plist",
                None,
                "Darwin",
            ),
        )
        for name, arguments, destination, prepare, uname in cases:
            with self.subTest(name=name):
                self.assert_symlink_is_replaced_without_touching_target(
                    arguments, destination, prepare=prepare, uname=uname,
                )

    def test_follower_config_clone_never_follows_a_dangling_symlink(self):
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            home, environment = self.environment(root)
            main = home / ".claude-token" / "config"
            main.parent.mkdir(parents=True)
            main.write_text("url=https://vault.invalid\ntoken=fixture\n")
            follower = home / ".claude-token" / "followers" / "fixture" / "config"
            follower.parent.mkdir(parents=True)
            victim = root / "unrelated" / "created-through-symlink"
            victim.parent.mkdir()
            follower.symlink_to(victim)

            result = self.run_token(environment, "claude", "install-follower-wrapper", "fixture")

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertFalse(victim.exists())
            self.assertFalse(follower.is_symlink())
            self.assertIn("mode=follower", follower.read_text())

    def test_crash_before_wrapper_replace_preserves_the_previous_launcher(self):
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            home, environment = self.environment(root)
            wrapper = home / "bin" / "codex"
            wrapper.parent.mkdir()
            wrapper.write_text("previous launcher\n")
            pathlib.Path(str(wrapper) + ".pre-codex-token").write_text("existing backup\n")
            environment["AI_TOKEN_TEST_CRASH_AT"] = "before-entrypoint-replace"

            result = self.run_token(environment, "codex", "install-wrapper")

            self.assertNotEqual(result.returncode, 0)
            self.assertEqual(wrapper.read_text(), "previous launcher\n")

    def test_crash_before_shell_rc_replace_preserves_the_startup_file(self):
        with tempfile.TemporaryDirectory() as directory:
            root = pathlib.Path(directory)
            home, environment = self.environment(root)
            config = home / ".claude-token" / "followers" / "fixture" / "config"
            config.parent.mkdir(parents=True)
            config.write_text("user=fixture\nmode=follower\n")
            startup = home / ".zshrc"
            before = "export KEEP=this\nalias claude-fixture='HOME=/tmp claude'\n"
            startup.write_text(before)
            environment["AI_TOKEN_TEST_CRASH_AT"] = "before-shell-rc-replace"

            result = self.run_token(environment, "claude", "install-follower-wrapper", "fixture")

            self.assertNotEqual(result.returncode, 0)
            self.assertEqual(startup.read_text(), before)

    def test_generated_state_paths_do_not_use_direct_truncating_writes(self):
        source = AI_TOKEN.read_text()
        for fragment in (
            'cat > "$w"',
            'cat > "$unit"',
            'cp "$main_config" "$follower_config"',
            'with open(path, "wb") as fh: plistlib.dump(data, fh)',
            'with open(path, "w") as fh:\n        fh.writelines(kept)',
        ):
            with self.subTest(fragment=fragment):
                if fragment in source:
                    self.fail(f"direct truncating generated-state write remains: {fragment}")


if __name__ == "__main__":
    unittest.main()
