#!/usr/bin/env python3
"""Supervision coverage audit: no emitted systemd unit without supervision.

Meta-guardrail for the 2026-07-22 blindness incident: it must stay
impossible for ai-token's proxy-install path to emit a systemd service that
has no semantic watchdog pairing and no explicit in-code exemption. The
audit extracts unit names from the install function at grep level (this is a
guardrail test, not a parser) and fails when any emitted service name lacks
both a `<name>-watchdog` sibling in the same code path and a
`# supervision-exempt: <name>` comment in ai-token.

The known gap is encoded, not ignored: the per-profile token proxy
(proxy.mjs generated by ai-token, serving 7801+) has no /healthz yet, so it
carries an explicit exemption comment in the code until it grows one.
"""

import pathlib
import re
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
AI_TOKEN = ROOT / "ai-token"

FUNCTION_RE = re.compile(r"^claude_cmd_proxy_install\(\) \{\n(.*?)^\}", re.S | re.M)
UNIT_FILE_RE = re.compile(r"\$unit_dir/([a-z0-9-]+\.(?:service|timer))\b")
SYSTEMCTL_RE = re.compile(r"systemctl --user[^\n]*?\b([a-z0-9-]+\.(?:service|timer))\b")
EXEMPT_RE = re.compile(r"^\s*# supervision-exempt: ([a-z0-9-]+)", re.M)


def emitted_unit_names(source):
    match = FUNCTION_RE.search(source)
    assert match, "claude_cmd_proxy_install() not found in ai-token"
    body = match.group(1)
    names = set(UNIT_FILE_RE.findall(body)) | set(SYSTEMCTL_RE.findall(body))
    return {name.rsplit(".", 1)[0] for name in names}


class SupervisionCoverageTest(unittest.TestCase):
    def test_every_emitted_service_is_supervised_or_explicitly_exempt(self):
        source = AI_TOKEN.read_text()
        units = emitted_unit_names(source)
        # Sanity: the audit must actually see the units the install path
        # emits — a broken/empty extraction must fail, never pass vacuously.
        self.assertIn("claude-any-proxy", units)
        self.assertIn("claude-token-proxy", units)
        self.assertIn("claude-any-proxy-watchdog", units)

        exempt = set(EXEMPT_RE.findall(source))
        unsupervised = sorted(
            name
            for name in units
            if not name.endswith("-watchdog")
            and f"{name}-watchdog" not in units
            and name not in exempt
        )
        self.assertEqual(
            [],
            unsupervised,
            "proxy-install emits units with no -watchdog pairing and no "
            "'# supervision-exempt: <name>' exemption: " + ", ".join(unsupervised),
        )

    def test_the_known_token_proxy_gap_is_encoded_explicitly(self):
        # claude-token-proxy (ai-token's generated per-profile proxy.mjs,
        # 7801+) has no /healthz yet: the audit encodes that gap as an
        # explicit exemption in the code instead of ignoring it.
        source = AI_TOKEN.read_text()
        self.assertIn("# supervision-exempt: claude-token-proxy", source)
        self.assertIn("no healthz yet", source)


if __name__ == "__main__":
    unittest.main()
